name: Go

on:
  push:
    branches: [ DEV ]
  pull_request:
    branches: [ DEV ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Checkout code into workspace directory
      uses: actions/checkout@v2
      
    - name: Install all Go dependencies
      run: go get

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
