name: Go

on:
  push:
    branches: [ DEV ]
  pull_request:
    branches: [ DEV ]

# jobs to run
jobs:
  
  # job 1: test go module
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      # step 1: set up go
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      
      # step 2: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      # step 3: install dependencies
      - name: Install all Go dependencies
        run: go get
      
      # step 4: run test
      - name: go test
        run: go test
